- change: removed
  target: route
  breaking: true
  deprecated: false
  doc_only: false
  note: Endpoint for accessing/managing a member’s scopes within a project (identified by project_id and member_id).
  paths: []
  date: '2026-04-12'
  diff_url: https://github.com/gr2m/ai-provider-monitor/pull/889
