- change: added
  target: route
  breaking: false
  deprecated: false
  doc_only: false
  note: Added GET /projects/{project_id}/users/{user_id}/roles/{role_id} to retrieve details of a specific project role assigned to a user, returning AssignedRoleDetails.
  paths: []
  date: '2026-08-24'
