- change: removed
  target: route
  breaking: true
  deprecated: false
  doc_only: false
  note: Removed endpoint for managing a specific project invite by member email at /v1/projects/{project_id}/invites/{email}.
  paths: []
  date: '2026-04-12'
