- change: removed
  target: route
  breaking: true
  deprecated: false
  doc_only: false
  note: Removed route /v1/projects/{project_id}/leave, which allowed a user to leave a project by its ID.
  paths: []
  date: '2026-04-12'
