- change: removed
  target: route
  breaking: true
  deprecated: false
  doc_only: false
  note: Route for operating on a specific model within a project via project_id and model_id path parameters.
  paths: []
  date: '2026-04-12'
