- change: added
  target: route
  breaking: false
  deprecated: false
  doc_only: false
  note: New endpoint retrieves details for an organization role assigned to a group by role_id, returning AssignedRoleDetails.
  paths: []
  date: '2026-08-24'
