- change: removed
  target: route
  breaking: true
  deprecated: false
  doc_only: false
  note: Endpoint for managing a specific self-hosted distribution credentials resource within a project, identified by distribution_credentials_id.
  paths: []
  date: '2026-04-12'
